# Generated by Django 2.2.2 on 2019-06-05 00:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Convenio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_convenio', models.IntegerField()),
                ('tipo', models.CharField(max_length=30)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_departamento', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Distrito',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_distrito', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_pais', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Plan_de_capacitacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_capacitacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Universidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_universidad', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Provincia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_provincia', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Institucion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_institucion', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('tipo', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=200)),
                ('pagina_web', models.CharField(max_length=30)),
                ('direccion', models.CharField(max_length=30)),
                ('ruc', models.IntegerField()),
                ('id_distrito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Distrito')),
            ],
        ),
        migrations.CreateModel(
            name='Facultad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_facultad', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('id_universidad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Universidad')),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_escuela', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Facultad')),
            ],
        ),
        migrations.AddField(
            model_name='distrito',
            name='id_provincia',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Provincia'),
        ),
        migrations.AddField(
            model_name='departamento',
            name='id_pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Pais'),
        ),
        migrations.CreateModel(
            name='Autoridad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_autoridad', models.IntegerField()),
                ('nombre', models.CharField(max_length=30)),
                ('apellido_paterno', models.CharField(max_length=30)),
                ('apellido_materno', models.CharField(max_length=30)),
                ('grado', models.CharField(max_length=15)),
                ('correo', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=15)),
                ('cargo', models.CharField(max_length=30)),
                ('id_facultad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Facultad')),
            ],
        ),
        migrations.CreateModel(
            name='Actividades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_actividades', models.IntegerField()),
                ('funcion_principal', models.CharField(max_length=50)),
                ('tareas_desprendidas', models.CharField(max_length=100)),
                ('id_capacitacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Plan_de_capacitacion')),
            ],
        ),
    ]
